from tkinter import*
root=Tk(className="sbi login page")
root.configure(bg="light blue")
root.geometry("600x400")
lbl=Label(root,text="please enter your login details:",relief="solid",width=25,font=("arial",19,"bold"))
lbl.place(x=65,y=120)
lbl=Label(root,text="gmail",font=("arial",10,"bold"))
lbl.place(x=50,y=180)
ent1=Entry(root,bd=5)
ent1.place(x=135,y=180)
lbl=Label(root,text="password",font=("arial",10,"bold"))
lbl.place(x=50,y=220)
ent=Entry(root,bd=5)
ent.place(x=135,y=220)
rd1=Radiobutton(root,text="savings account",value=1)
rd1.place(x=120,y=250)
rd1=Radiobutton(root,text="Fixed deposit",value=2)
rd1.place(x=250,y=250)
def close():
    root.destroy()
def login():
    root1=Tk()
    root1.title("sbi")
    root1.geometry("200x200")
    root1.configure(bg="light blue")
    lbl=Label(root1,text="welcome to sbi")
    lbl.grid(row=0,column=1)
    def moneywithdraw():
        root4=Tk()
        root4.title("moneywithdraw")
        root4.geometry("500x500")
        root4.configure(bg="light blue")
        lbl=Label(root4,text="ammount to withdraw:")
        lbl.place(x=30,y=40)
        ent=Entry(root4,bd=5)
        ent.place(x=170,y=40)
        def close1():
            root4.destroy()
        def withdraw():
            messagebox.showinfo("note","take the cash from the below")
        btn=Button(root4,text="submit",command=[withdraw()])
        btn.place(x=150,y=80)
        btn=Button(root4,text="Back",command=close1)
        btn.place(x=200,y=80)
    def accountbalance(): 
        root2=Tk()
        root2.title("account balance")
        root2.geometry("200x200")
        root2.configure(bg="light blue")
        
    def bankstatement():
        root3=Tk()
        root3.title("bankstatement")
        root3.geometry("400x400")
        root3.configure(bg="light blue")
        lbl=Label(root3,text="enter your mail:")
        lbl.place(x=20,y=20)
        ent=Entry(root3,bd=5)
        ent.place(x=120,y=20)
        def close2():
            root3.destroy()
        def withdraw():
            messagebox.showinfo("note","the bank statement sent to your mail id")
        btn=Button(root3,text="submit",command=withdraw)
        btn.place(x=150,y=80)
        btn=Button(root3,text="Back",command=close2)
        btn.place(x=200,y=80)
    btn=Button(root1,text="account balance",command=accountbalance)
    btn.grid(row=3,column=2)
    btn=Button(root1,text="bankstatement",command=bankstatement)
    btn.grid(row=4,column=2)
    btn=Button(root1,text="moneywithdraw",command=moneywithdraw)
    btn.grid(row=5,column=2)
btn=Button(root,text="login",command=lambda:[login(),close()])
btn.place(x=190,y=300)  

root.mainloop()